# Generated by Django 3.1.1 on 2020-09-03 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('role', models.PositiveSmallIntegerField(choices=[(2, 'Editor'), (1, 'Writer')], default=1, help_text='Writer = 1, Editor = 2')),
            ],
        ),
    ]
